name: Docker Image CI

on:
  push:
    branches: [ "deploy" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - run: ls
    
    - name: install dependencies
      run: pip install --no-cache-dir -r requirements.txt
    
    - name: deploy
      run: Copy-Item -Path ./* -Destination "C:\Program Files\sise.micro-message-rna-project\be\sise.micro-rna-m-rna-targets-interactions.backend\deploy" -Recurse -Force
    
    - name: Restart Python
      uses: actions/virtual-environments/windows-2019/microsoft-windows-task-scheduler@main
      with:
        task-name: 'python-on-start'
        action: 'run'
